replicaCount: 1

image:
  repository: minio/minio
  tag: latest

minio:
  rootUser: minioadmin
  rootPassword: minioadmin123
  browser: "on"
  consoleAddress: ":9090"
  existingClaim: ""

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"

storage:
  size: 1Gi

inferenceServiceUrl: http://triton.runai-test.svc.cluster.local
